# Generated by Django 6.0.1 on 2026-02-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_emailuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nameUser',
        ),
    ]
