# Generated by Django 6.0.1 on 2026-02-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_nameuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(default=123, max_length=200, verbose_name='interest'),
            preserve_default=False,
        ),
    ]
